# Tensors with PyTorch

There are many libraries that can be used to work with tensors. Here we will use [PyTorch](https://pytorch.org) a Python library for deep learning. It is based on the Torch library, which was developed by Facebook's AI Research lab (FAIR) - now Meta. PyTorch is a Python package that provides two high-level features:

1. Tensor computation (like NumPy) with strong GPU acceleration

2. Deep neural networks built on a tape-based autograd system

Note that JAX is also a good alternative to PyTorch and is used in the [Flax](https://flax.readthedocs.io/en/latest/) library. It offers a numpy API and offers autograd capabilities (see the  backpropagation chapter). JAX enforces functional programming and is more suitable for research and prototyping.

In this notebook we will learn how to use and manipulate [Pytorch tensors](https://pytorch.org/docs/stable/tensors.html). We will also learn how to use the GPU to accelerate our computations. 

In [2]:
import torch
from PIL import Image
import requests
from torchvision.io import read_image
import torchvision.transforms as transforms


Lets create a tensor of a certian shape and see what is its type and the reported type for one of its elements.  

In [3]:
n = 100
x = torch.ones(n)
print(x)
print('type of x:', type(x))
print('shape of x:', x.shape)
print('type of x[0]:', type(x[0]))


tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])
type of x: <class 'torch.Tensor'>
shape of x: torch.Size([100])
type of x[0]: <class 'torch.Tensor'>


A tensor of specific data type can be constructed by passing a torch.dtype. Note that the default data type is `torch.float32` and the dynamic range of the tensor elements that we create can have a profound effect on both the computational efficiency and performance of models we create.  


In [4]:
torch.zeros([2, 4], dtype=torch.int32)

tensor([[0, 0, 0, 0],
        [0, 0, 0, 0]], dtype=torch.int32)

We can also instantiate a tensor in either in the RAM of our host  or straight into the RAM of an  accelerator that the host has access to. 

In [5]:
cuda0 = torch.device('cuda:0')
x = torch.tensor([[1, 2, 3], [4, 5, 6]], dtype=torch.float64, device=cuda0)
x

tensor([[1., 2., 3.],
        [4., 5., 6.]], device='cuda:0', dtype=torch.float64)

## Slicing operations

In [6]:
print(x[:,1]) # get the 2nd column of x
print(x[-1,:]) # get the last row of x

tensor([2., 5.], device='cuda:0', dtype=torch.float64)
tensor([4., 5., 6.], device='cuda:0', dtype=torch.float64)


## Batch operations and images

Note that the color channels are always on the 3rd dimension **from the end**. 

In [7]:
batch_t = torch.randn(2, 3, 5, 5) # shape [batch, channels, rows, columns]
batch_gray_naive = batch_t.mean(-3)

batch_gray_naive.shape

torch.Size([2, 5, 5])

In [26]:
# MS COCO image
url = "https://farm8.staticflickr.com/7399/8727969852_13c0f43ae9_z.jpg"
image = Image.open(requests.get(url, stream=True).raw)

transform = transforms.Compose([
transforms.PILToTensor()])

torch_image = transform(image)
torch_image.shape

print('Number of channels:', torch_image.shape[-3])
print('Number of height pixels:', torch_image.shape[-2])
print('Number of width pixels:', torch_image.shape[-1])

# average the image across the channels
torch_image =  torch_image.float() 
torch_image /= 255.0

# introduce batch dimension
torch_image = torch_image.unsqueeze(0)

torch_image.shape

# means of each channel
means = torch_image.mean(dim=(2,3))

# var of each channel
vars = torch_image.var(dim=(2,3))



Number of channels: 3
Number of height pixels: 424
Number of width pixels: 640
